### ISSUE TITLE
QUESTION: How to pass a /dev/tty* in docker-compose file

### ISSUE THREAD

**Issue by 2Fake** [BrutalBirdie/eze-openHAB-docker#4]
Hi,

thank you for the image. I will try it after christmas ;).

Can you tell me how to pass a /dev/tty* device (Z-Wave stick) in the docker compose file?

Best regards
Markus

**Comment by BrutalBirdie** [comment]
You should be able to add this to your docker-compose file.
```
devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
```
There is also a very good post see
https://community.openhab.org/t/how-to-add-zigbee-usb-controller-to-oh-docker-via-portainer/74164/10?u=brutalbirdie
or
https://community.openhab.org/t/running-openhab-2-in-docker/14267
