### ISSUE TITLE
How to install on portainer?

### ISSUE THREAD

**Issue by Norin-Radd** [BrutalBirdie/eze-openHAB-docker#5]
Hi,

i would like to install this on my libreelec on rpi3.

But I don't figure out how.

**Comment by BrutalBirdie** [comment]
So you want to run the setup not via scripts but via. the Portainer UI?
A better description of what you want to achieve would be great since I don't understand exactly what you are planning to do.

All I know is "I want to use Portainer on RPI3 und don't know how"

**Comment by Norin-Radd** [comment]
Yes, i managed to install dockerhub official image of openhab, but couldn't link things, I thought this was an image I could install via portainer.

**Comment by BrutalBirdie** [comment]
If there is a problem with linking chanels / things this should be a question in the openHAB community not in this repo.

I also use the official openHAB Docker image so there is no difference.
I just added some components like influxdb, grafana, mosquitto und node-red.

Please direct your question to the openHAB Community.

https://community.openhab.org/t/how-to-ask-a-good-question-help-us-help-you/58396?u=brutalbirdie
