### ISSUE TITLE
Nodered

### ISSUE THREAD

**Issue by MaltheSurrow** [BrutalBirdie/eze-openHAB-docker#6]
Hi,
Nodered has updated their path on docker, it was Node-red-docker it is now node-red.

**Comment by BrutalBirdie** [comment]
Thanks @MaltheSurrow for pointing this out, sorry the fix took so long.
I simply did not see the issue 😬

**Comment by MaltheSurrow** [comment]
Hi, 
I just saw an error when tried to install and it was a pretty easy fix. You are welcome.
Fra: Elias Hackradt
Sendt: 5. maj 2021 00:34
Til: BrutalBirdie/eze-openHAB-docker
Cc: MaltheSurrow; Mention
Emne: Re: [BrutalBirdie/eze-openHAB-docker] Nodered (#6)

Thanks @MaltheSurrow for pointing this out, sorry the fix took so long.
I simply did not see the issue 😬
